In [1]:
import tensorflow as tf

c:\users\katta\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\katta\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\katta\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\katta\appd

In [2]:
print(tf.__version__)

1.14.0


In [3]:
hello = tf.constant('hello')

In [4]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
a = tf.constant(10)

In [6]:
b = tf.constant(20)

In [7]:
a+b

<tf.Tensor 'add:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    print(sess.run(hello))
    print(a+b)
    print(sess.run(a+b))
    result=sess.run(a+b)

b'hello'
Tensor("add_4:0", shape=(), dtype=int32)
30


In [14]:
print(result)

30


In [15]:
const = tf.fill((4,4), 1)

In [17]:
with tf.Session() as sess:
    print(sess.run(const))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
my_zeros = tf.zeros((4,4,4))
my_ones = tf.ones((4,4))

In [35]:
with tf.Session() as sess:
    print(sess.run(my_zeros))
    print(sess.run(my_ones))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
myrand = tf.random_normal((4,4), mean =10, stddev =80)

In [37]:
with tf.Session() as sess:
    print(sess.run(myrand))

[[  39.019363  183.31483    28.323587 -238.95572 ]
 [ -47.645233   79.07919    27.612919   28.165714]
 [ -13.106468  101.13763   122.008026  151.29718 ]
 [ -87.00042    70.72542   -46.79303    10.069735]]


In [38]:
my_uni_rand = tf.random_uniform((4,4), minval=10, maxval=100)

In [39]:
with tf.Session() as sess:
    print(sess.run(my_uni_rand))

[[34.284172 20.019585 82.91444  64.62268 ]
 [53.39767  52.55641  17.549248 69.32944 ]
 [24.122324 49.409073 99.1723   97.90122 ]
 [78.79282  26.997427 44.050964 93.95136 ]]


In [40]:
my_ops = [const, my_zeros, my_ones, myrand,my_uni_rand]

In [41]:
sess = tf.InteractiveSession()

In [43]:
for opn in my_ops:
    print(sess.run(opn))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 127.492584   58.122498   33.07603  -169.51158 ]
 [ -62.668755   95.351974   71.9312     30.795818]
 [  22.194118   19.593689 -182.24794    35.42496 ]
 [ 175.08365    10.866293  -57.46006    89.9548  ]]
[[62.362858 19.778551 45.515507 57.534912]
 [70.603355 13.301392 31.597319 75.23835 ]
 [32.53476  23.819975 95.47768  84.10978 ]
 [49.12033  26.373524 96.49306  62.31081 ]]


In [45]:
for opn in my_ops:
    print(opn.eval())

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[  26.674456   47.63454   129.81831   147.93184 ]
 [  63.094406   10.823511   16.766573   22.585644]
 [ -40.06227  -127.550674  -47.902435   71.15367 ]
 [  41.995514  156.81589    88.28553    91.62536 ]]
[[69.18237  73.9609   56.82267  28.459671]
 [94.941246 57.166046 54.31668  38.587303]
 [36.41626  67.91315  89.473495 74.17853 ]
 [36.06341  54.767475 82.284996 51.29323 ]]


In [47]:
a = tf.constant([[1,2], [3,4]])

In [48]:
print(a.get_shape())

(2, 2)


In [49]:
b = tf.constant([[10], [100]])

In [50]:
mul = tf.matmul(a,b)

In [52]:
mul.eval() # This is equls to sess.run

array([[210],
       [430]])